javascripts:
  app:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery_ujs.js
    - public/javascripts/vendor/jquery-ui.js
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/backbone.js
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/vendor/backbone.localStorage.js

    - app/views/jst/**/*.jst
    - public/javascripts/application.js
    - public/javascripts/coffee/models.js
    - public/javascripts/coffee/prefs.js
    - public/javascripts/coffee/views.js
    - public/javascripts/coffee/routes.js
stylesheets:
  app:
    - public/stylesheets/*.css
