development:
  host: localhost
  database: coffeeprefs_development

test:
  host: localhost
  database: coffeeprefs_test

# set these environment variables on your prod server
production:
<% if ENV['MONGOLAB_URI'] %>
  uri: <%= ENV['MONGOLAB_URI'] %>
<% else %>
  host: localhost
  database: coffeeprefs_development
<% end %>
  
  # not needed for heroku / mongolab
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
